import 'package:wecheck/model/group_chat.dart';
import 'package:wecheck/model/message.dart';

class ChatDetailRepository {
  Future<List<UserMessage>> doGetListUserMessage() {
    var messages = [
      UserMessage(
        "1",
        " this ",
        "2022-05-18 00:00:00",
        1,
        User("https://www.w3schools.com/howto/img_avatar.png", "People 1"),
      ),
      UserMessage(
        "2",
        "this is message description this is message description  this is message description  this is message description  this is message description  this is message description  this is message description  this is message description  this is message description  this is message description  this is message description ",
        "2022-05-18 01:00:00",
        1,
        User("https://www.w3schools.com/howto/img_avatar.png", "People 1"),
      ),
      UserMessage(
        "3",
        "this is message description this is message description  this is message description  this is message description  this is message description  this is message description  this is message description  this is message description  this is message description ",
        "2022-05-18 02:00:00",
        2,
        User("https://www.w3schools.com/w3images/avatar6.png", "People 1"),
      ),
      UserMessage(
        "4",
        "this is message description",
        "2022-05-18 03:00:00",
        1,
        User("https://www.w3schools.com/w3images/avatar2.png", "People 1"),
      ),
      UserMessage(
        "5",
        "this",
        "2022-05-18 04:00:00",
        2,
        User("https://www.w3schools.com/w3images/avatar6.png", "People 1"),
      ),
      UserMessage(
        "6",
        "this is message description",
        "2022-05-18 05:00:00",
        2,
        User("https://www.w3schools.com/w3images/avatar6.png", "People 1"),
      ),
      UserMessage(
        "7",
        "this is message description",
        "2022-05-18 06:00:00",
        1,
        User("https://www.w3schools.com/howto/img_avatar.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 07:00:00",
        1,
        User("https://www.w3schools.com/w3images/avatar2.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 08:00:00",
        1,
        User("https://www.w3schools.com/howto/img_avatar.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 09:00:00",
        1,
        User("https://www.w3schools.com/w3images/avatar2.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 10:00:00",
        1,
        User("https://www.w3schools.com/howto/img_avatar.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 11:00:00",
        2,
        User("https://www.w3schools.com/w3images/avatar6.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 12:00:00",
        1,
        User("https://www.w3schools.com/w3images/avatar2.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 13:00:00",
        2,
        User("https://www.w3schools.com/w3images/avatar6.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 14:00:00",
        1,
        User("https://www.w3schools.com/howto/img_avatar.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 15:00:00",
        2,
        User("https://www.w3schools.com/w3images/avatar6.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 16:00:00",
        2,
        User("https://www.w3schools.com/w3images/avatar6.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 17:00:00",
        1,
        User("https://www.w3schools.com/howto/img_avatar.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 18:00:00",
        2,
        User("https://www.w3schools.com/w3images/avatar6.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 19:00:00",
        1,
        User("https://www.w3schools.com/w3images/avatar2.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 20:00:00",
        2,
        User("https://www.w3schools.com/w3images/avatar6.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 21:00:00",
        1,
        User("https://www.w3schools.com/howto/img_avatar.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 22:00:00",
        2,
        User("https://www.w3schools.com/w3images/avatar6.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 23:00:00",
        1,
        User("https://www.w3schools.com/w3images/avatar2.png", "People 1"),
      ),
      UserMessage(
        "8",
        "this is message description",
        "2022-05-18 24:00:00",
        2,
        User("https://www.w3schools.com/w3images/avatar6.png", "People 1"),
      ),
    ];
    return Future.value(messages);
  }
}
